version: "3.7"

services:
  flaskdocker:
    container_name: python-client-satisfaction
    build:
      context: .
      dockerfile: './DockerFile'
    ports: 
      - "5000:5000"
    volumes:
      - './:/app'
    links:
      - database-client-satisfaction:database-client-satisfaction
    networks:
      - python
        
  database-client-satisfaction:
    container_name: database-client-satisfaction
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: client_satisfaction_db
    networks:
      - mysql-phpmyadmin
      - python

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - database-client-satisfaction
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: database-client-satisfaction
    networks:
      - mysql-phpmyadmin

networks:
  local:
  mysql-phpmyadmin:
  python:

volumes:
  dbdata:
    driver: local
