FROM python:3.11.6

WORKDIR /app

COPY requirements.txt /app/requirements.txt

#RUN python3 -m pip install --upgrade pip virtualenv \
#    && python3 -m venv .venv \
#    && . .venv/bin/activate \
#    && pip install --upgrade pip

# Install the required system dependencies
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

# Create a virtual environment and activate it
RUN python3 -m venv .venv && \
    . .venv/bin/activate && \
    pip install --upgrade pip
    
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt \
    && pip cache purge

COPY . /app

ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0

EXPOSE 5000

CMD ["flask", "run"]
